! ##################################################################################################################################
! Begin MIT license text.
! _______________________________________________________________________________________________________

! Copyright 2022 Dr William R Case, Jr (mystransolver@gmail.com)

! Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
! associated documentation files (the "Software"), to deal in the Software without restriction, including
! without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to
! the following conditions:

! The above copyright notice and this permission notice shall be included in all copies or substantial
! portions of the Software and documentation.

! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
! OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
! THE SOFTWARE.
! _______________________________________________________________________________________________________

! End MIT license text.

SUBROUTINE PRINT_BUILD_INFO (PRINT_LICENSES)

   USE IOUNT1, ONLY: SC1
   IMPLICIT NONE

   LOGICAL, INTENT(IN) :: PRINT_LICENSES

! Non-license case: build metadata (timestamp, compiler, flags, solver)
! followed by the list of statically-linked libraries.
!
! License case: full OSS license text for every bundled library.
!
! All PRINT_* helpers are auto-generated by CMakeLists.txt at configure
! time into Source/INCLUDE/BUILD_INFO_GENERATED.F90.inc and
! Source/INCLUDE/STATIC_LICENSES_GENERATED.F90.inc.

   IF (.NOT. PRINT_LICENSES) THEN
      CALL PRINT_BUILD_CONSTANTS(SC1)
      WRITE(SC1,'(A)') ' '
      CALL PRINT_STATIC_LIB_LIST(SC1)
      WRITE(SC1,'(A)') ' To see licenses for the static libraries, use --licenses.'
      WRITE(SC1,'(A)') ' '
   ELSE
      CALL PRINT_ALL_LICENSES(SC1)
   END IF

END SUBROUTINE PRINT_BUILD_INFO

#include <STATIC_LICENSES_GENERATED.F90.inc>
#include <BUILD_INFO_GENERATED.F90.inc>
